juegosCom/juegosApp/urls.py
from django.contrib import admin
from django.urls import path
from juegosApp.views import listar_juegos,listar_juegos_gratis , crear_juego, buscar_juego, crear_juego_gratis, buscar_juego_gratis, eliminar_juego, editar_juego, editar_juego_gratis, eliminar_juego_gratis, mostrar_juego, mostrar_juego_gratis


urlpatterns = [
    path('juegos/', listar_juegos, name='listar_juegos'),
    path('juegos-gratis/', listar_juegos_gratis, name='listar_juegos_gratis'),
    path('crear-juego/', crear_juego, name='crear_juego'),
    path('crear-juego-gratis/', crear_juego_gratis, name='crear_juego_gratis'),
    path('buscar-juego/', buscar_juego, name='buscar_juego'),
    path('buscar-juego-gratis/', buscar_juego_gratis, name='buscar_juego_gratis'),
    path('eliminar-juego/<int:id>/', eliminar_juego, name='eliminar_juego'),
    path('editar-juego/<int:id>/', editar_juego, name='editar_juego'),
    path('eliminar-juego-gratis/<int:id>/', eliminar_juego_gratis, name='eliminar_juego_gratis'),
    path('editar-juego-gratis/<int:id>/', editar_juego_gratis, name='editar_juego_gratis'),
    path('mostrar-juego/<int:id>/', mostrar_juego, name='mostrar_juego'),
    path('mostrar-juego-gratis/<int:id>/', mostrar_juego_gratis, name='mostrar_juego_gratis'),
]

juegosCom/juegosCom/urls.py
from django.contrib import admin
from django.urls import path, include
from juegosCom.views import index 
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", index, name='inicio'),
    path('admin/', admin.site.urls),  
    path("catalogo/", include("juegosApp.urls")),
    path("perfiles/", include("perfiles.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

juegosCom/perfiles/urls.py
from django.contrib import admin
from django.urls import path



from perfiles.views import registro, login_view, CustomLogoutView, MiPerfilUpdateView, agregar_avatar, eliminar_avatar


urlpatterns = [
    path('registro/', registro, name='registro'),
    path('login/', login_view, name="login"),
    path('logout/', CustomLogoutView.as_view(), name="logout"),
    path('editar-mi-perfil/', MiPerfilUpdateView.as_view(), name="editar_perfil"),
    path('agregar-avatar/', agregar_avatar, name="agregar_avatar"),
    path('eliminar-avatar/', eliminar_avatar, name="eliminar_avatar"),
]

juegosCom/juegosApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
#JUEGOS-PAGOS-------->

#JUEGOS-PAGOS-------->
class Stock(models.Model):
    nombre = models.CharField(max_length=100)
    costo = models.IntegerField()

class PayGames(models.Model): 
    nombre = models.CharField(max_length=100)
    genero = models.CharField(max_length=40)
    descripcion = models.CharField(max_length=500)
    lanzamiento = models.DateField()
    clasificacion = models.IntegerField()
    costo = models.IntegerField()
    creador = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.nombre}, {self.costo}'
        

#JUEGOS-GRATIS-------->
class FreeStock(models.Model):
    nombre = models.CharField(max_length=100)
    costo = models.IntegerField()

class FreeGames(models.Model):
    nombre =models.CharField(max_length=100)
    genero =models.CharField(max_length=40)
    descripcion = models.CharField(max_length=256)
    lanzamiento = models.DateField(max_length=20)
    clasificacion = models.IntegerField()
    creador = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.nombre}'
    
class Carrito(models.Model):
    cantidad_articulos = models.PositiveIntegerField(default=0)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    costo_total = models.DecimalField(max_digits=10, decimal_places=2, default=0)

juegosCom/juegosApp/forms.py
from django import forms

#JUEGOS FORM
class juegoForm(forms.Form):
    nombre = forms.CharField(required=True, max_length=64)
    descripcion = forms.CharField(required=True, max_length=500, widget=forms.Textarea)
    genero = forms.CharField(required=True, max_length=40)
    lanzamiento = forms.DateField(required=True, widget=forms.DateInput(attrs={'placeholder': 'YYYY-MM-DD'}))
    clasificacion = forms.IntegerField(required=True, max_value=18)
    costo = forms.IntegerField(required=True, max_value=30000)


#JUEGOS GRATIS FORM
class juegoGratisForm(forms.Form):
    nombre = forms.CharField(required=True, max_length=64)
    descripcion = forms.CharField(required=True, max_length=500, widget=forms.Textarea)
    genero = forms.CharField(required=True, max_length=40)
    lanzamiento = forms.DateField(required=True, widget=forms.DateInput(attrs={'placeholder': 'YYYY-MM-DD'}))
    clasificacion = forms.IntegerField(required=True, max_value=18)

juegosCom/juegosApp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from juegosApp.models import PayGames, FreeGames, Carrito
from juegosApp.forms import juegoForm, juegoGratisForm
from django.contrib.auth.decorators import login_required
# Create your views here.


# VISTA JUEGOS PAGOS.

def listar_juegos(request):
    contexto = {
        'PayGames' : PayGames.objects.all(), 
    }
    http_response = render(
        request=request,
        template_name='juegosApp/juegos_pagos.html',
        context=contexto,
    )
    return http_response

# VISTA JUEGOS GRATIS.

def listar_juegos_gratis(request):
    contexto = {
        'FreeGames' :FreeGames.objects.all(), 
    }
    http_response = render(
        request=request,
        template_name='juegosApp/juegos_gratis.html',
        context=contexto,
    )
    return http_response

# VISTA FORMULARIOS JUEGOS GRATIS.
@login_required
def crear_juego_gratis(request):
    if request.method == "POST":
        formulario = juegoGratisForm(request.POST)
        
        if formulario.is_valid():
            data = formulario.cleaned_data
            nombre = data["nombre"]
            descripcion = data["descripcion"] 
            genero = data["genero"]  
            lanzamiento = data["lanzamiento"]
            clasificacion = data["clasificacion"]
            creador = request.user
            FreeGame= FreeGames(nombre=nombre, descripcion=descripcion, lanzamiento=lanzamiento, clasificacion=clasificacion, genero=genero, creador=creador)
            FreeGame.save()
        
            url_exitosa = reverse('listar_juegos_gratis')
            return redirect(url_exitosa)
    else:
        formulario = juegoGratisForm()
    http_response = render(
        request=request,
        template_name='juegosApp/valid_forms_gratis.html', 
        context={'formulario':formulario}
    )
    return http_response

# VISTA FORMULARIOS JUEGOS PAGOS.
@login_required
def crear_juego(request):
    if request.method == "POST":
        formulario = juegoForm(request.POST)
        
        if formulario.is_valid():
            data = formulario.cleaned_data
            nombre = data["nombre"]
            descripcion = data["descripcion"] 
            genero = data["genero"]  
            lanzamiento = data["lanzamiento"]
            clasificacion = data["clasificacion"]
            costo = data["costo"]
            creador = request.user
            PayGame= PayGames(nombre=nombre, descripcion=descripcion, costo=costo, lanzamiento=lanzamiento, clasificacion=clasificacion, genero=genero, creador=creador)
            PayGame.save()
        
            url_exitosa = reverse('listar_juegos')
            return redirect(url_exitosa)
    else:
        formulario = juegoForm()
    http_response = render(
        request=request,
        template_name='juegosApp/valid_forms.html', 
        context={'formulario':formulario}
    )
    return http_response


# VISTAS BUSQUEDAS.
def buscar_juego(request):
    if request.method == "POST":
        data = request.POST
        busqueda = data["busqueda"]
        PayGame = PayGames.objects.filter(costo__exact=busqueda,)
    
    contexto = {
            "PayGames":PayGame,
        }
    http_response = render(
            request=request,
            template_name='juegosApp/juegos_pagos.html',
            context=contexto,
        )
    return http_response

# VISTAS BUSQUEDAS GRATIS.
def buscar_juego_gratis(request):
    
    if request.method == "POST":
        data = request.POST
        busqueda = data["busqueda"]
        FreeGame = FreeGames.objects.filter(genero__contains=busqueda)
    
    contexto = {
            "FreeGames":FreeGame,
        }
    http_response = render(
            request=request,
            template_name='juegosApp/juegos_gratis.html',
            context=contexto,
        )
    return http_response

# VISTAS ELIMINAR JUEGOS. 
@login_required
def eliminar_juego(request, id):
    juego = PayGames.objects.get(id=id)
    if request.method == "POST":
        juego.delete()
        
        url_exitosa = reverse('listar_juegos')
        return redirect(url_exitosa)
    
    return render(
        request=request,
        template_name='juegosApp/confirm_delete.html', 
        context={'juego':juego}
    )

# VISTAS ELIMINAR JUEGOS GRATIS. 
@login_required
def eliminar_juego_gratis(request, id):
    juego = FreeGames.objects.get(id=id)
    if request.method == "POST":
        juego.delete()
        
        url_exitosa = reverse('listar_juegos_gratis')
        return redirect(url_exitosa)
    
    return render(
        request=request,
        template_name='juegosApp/confirm_delete_gratis.html', 
        context={'juego':juego}
    )

# VISTAS EDITAR JUEGOS. 
@login_required
def editar_juego(request, id):
    PayGame = PayGames.objects.get(id=id) 
    if request.method == "POST":
        formulario = juegoForm(request.POST)
        
        if formulario.is_valid():
            data = formulario.cleaned_data
            PayGame.nombre = data["nombre"]
            PayGame.descripcion = data["descripcion"] 
            PayGame.genero = data["genero"]  
            PayGame.lanzamiento = data["lanzamiento"]
            PayGame.clasificacion = data["clasificacion"]
            PayGame.costo = data["costo"]
            PayGame.save()
            url_exitosa = reverse('listar_juegos')
            return redirect(url_exitosa)
    else:
        inicial = {
            'nombre' : PayGame.nombre,
            'descripcion' : PayGame.descripcion,
            'genero' : PayGame.genero, 
            'lanzamiento' : PayGame.lanzamiento,
            'clasificacion' : PayGame.clasificacion,
            'costo' : PayGame.costo,
            }
        formulario = juegoForm(initial=inicial)
    return render(
        request=request,
        template_name='juegosApp/editar_juego.html', 
        context={'formulario':formulario}
    )
    
# VISTAS EDITAR JUEGOS GRATIS. 
@login_required
def editar_juego_gratis(request, id):
    FreeGame = FreeGames.objects.get(id=id) 
    if request.method == "POST":
        formulario = juegoGratisForm(request.POST)
        
        if formulario.is_valid():
            data = formulario.cleaned_data
            FreeGame.nombre = data["nombre"]
            FreeGame.descripcion = data["descripcion"] 
            FreeGame.genero = data["genero"]  
            FreeGame.lanzamiento = data["lanzamiento"]
            FreeGame.clasificacion = data["clasificacion"]
            FreeGame.save()
            url_exitosa = reverse('listar_juegos_gratis')
            return redirect(url_exitosa)
    else:
        inicial = {
            'nombre' : FreeGame.nombre,
            'descripcion' : FreeGame.descripcion,
            'genero' : FreeGame.genero, 
            'lanzamiento' : FreeGame.lanzamiento,
            'clasificacion' : FreeGame.clasificacion,
            }
        formulario = juegoGratisForm(initial=inicial)
    return render(
        request=request,
        template_name='juegosApp/editar_juego_gratis.html', 
        context={'formulario':formulario}
    )

# VISTA MOSTRAR INFO JUEGOS. 
def mostrar_juego(request, id):
    PayGame = PayGames.objects.get(id=id) 
    contexto = {
        'PayGame':PayGame,
    }

    return render(request,'juegosApp/juegos_pagos_info.html', contexto)

# VISTA MOSTRAR INFO JUEGOS GRATIS. 
def mostrar_juego_gratis(request, id):
    FreeGame = FreeGames.objects.get(id=id) 
    contexto = {
        'FreeGame':FreeGame,
    }

    return render(request,'juegosApp/juegos_gratis_info.html', contexto)

juegosCom/juegosApp/templates/juegosApp/confirm_delete.html
{% extends "perfiles/index.html" %}

{% block content %}

<section class="section-delete">
    <div class="card">
        <div class="titles">
            <h1>Confirmar borrado</h1>
            <h3>¿Estás seguro de que deseas borrar el artículo?</h3>
        </div>
        

        <form method="POST" action="{% url 'eliminar_juego' juego.id %}">
            {% csrf_token %}
        
            <input class="btn btn-danger" type="submit" value="Confirmar"/>
        </form>
    </div>
</section>

{% endblock content %}

juegosCom/juegosApp/templates/juegosApp/confirm_delete_gratis.html
{% extends "perfiles/index.html" %}

{% block content %}

<section class="section-delete">
    <h4>Confirmar borrado</h4>
    <p>¿Estás seguro de que deseas borrar el artículo?</p>

    <form method="POST" action="{% url 'eliminar_juego_gratis' juego.id %}">
        {% csrf_token %}
    
        <input type="submit" value="Confirmar"/>
    </form>
</section>

{% endblock content %}

juegosCom/juegosApp/templates/juegosApp/editar_juego.html
{% extends "perfiles/index.html" %}

{% block content %}
<section class="section-4">
  <div>
    <h1>Edita tu videojuego</h1>
    
    <form method="POST">
        {% csrf_token %}
        
        <div class="form-group">
          <label for="id_nombre">Nombre:</label>
          {{ formulario.nombre }}
        </div>
        
        <div class="form-group-desc">
          <label for="id_descripcion">Descripción:</label>
          {{ formulario.descripcion }}
        </div>
        
        <div class="form-group">
          <label for="id_genero">Género:</label>
          {{ formulario.genero }}
        </div>
        
        <div class="form-group">
          <label for="id_lanzamiento">Lanzamiento:</label>
          {{ formulario.lanzamiento }}
        </div>
        
        <div class="form-group">
          <label for="id_clasificacion">Clasificación:</label>
          {{ formulario.clasificacion }}
        </div>
        
        <div class="form-group">
          <label for="id_costo">Costo:</label>
          {{ formulario.costo }}
        </div>
        
        <button class="btn btn-light" type="submit">Enviar</button>
      </form>
    </div>
</section>
{% endblock content %}

juegosCom/juegosApp/templates/juegosApp/editar_juego_gratis.html
{% extends "perfiles/index.html" %}

{% block content %}
<section class="section-4">
  <div>
    <h1>Edita tu videojuego</h1>
    
    <form method="POST">
        {% csrf_token %}
        
        <div class="form-group">
          <label for="id_nombre">Nombre:</label>
          {{ formulario.nombre }}
        </div>
        
        <div class="form-group-desc">
          <label for="id_descripcion">Descripción:</label>
          {{ formulario.descripcion }}
        </div>
        
        <div class="form-group">
          <label for="id_genero">Género:</label>
          {{ formulario.genero }}
        </div>
        
        <div class="form-group">
          <label for="id_lanzamiento">Lanzamiento:</label>
          {{ formulario.lanzamiento }}
        </div>
        
        <div class="form-group">
          <label for="id_clasificacion">Clasificación:</label>
          {{ formulario.clasificacion }}
        </div>
        
        <button class="btn btn-light" type="submit">Enviar</button>
      </form>
    </div>
</section>
{% endblock content %}

juegosCom/juegosApp/templates/juegosApp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
</head>
<body>
  <script src="https://www.paypal.com/sdk/js?client-id=EPKD6WVaYpqx9P82NnEpGBsN1M55-uD3pko1PZs3BZXtOtbHHH7lJVmJ7mXFs56CEhz7EptH63Djlzee"> 
  </script>
    <header>
        <div class="nav">
           <h1 class="h1"> JuegosCom </h1>

           <nav class="navbar">
              <a class="nav-item" href="{% url 'inicio' %}">Inicio</a>
              <a class="nav-item" href="{% url 'listar_juegos' %}">Juegos</a>
              <a class="nav-item" href="{% url 'listar_juegos_gratis' %}">Free to play</a>
              {% if user.is_authenticated %}
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <div style= "display: inline-flex;">
                    <span>{{user.username}}</span>
                  </div>
                </button>
                <ul class="dropdown-menu">
                <li>
                  <a class="dropdown-item" href="{% url 'editar_perfil' %}">Editar tus datos.</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'agregar_avatar' %}">Agregar avatar</a>
                </li>
                <li>
                  <a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesion.</a>
                </li>
                </ul>
              </div>
              {% else %}
              <a class="nav-item" href="{% url 'login' %}">Iniciar Sesion</a>
              <a class="nav-item" href="{% url 'registro' %}">Registro</a>
              {% endif %}
           </nav>
        </div>
    </header>

    <main>
        <section class="wrapper">
            <article>
                <div class="carousel">
                    <div class="slider">
                        <img id="slide-1" src="{% static 'images/rocket-league.jpeg' %}" alt="">
    
                        <img id="slide-2" src="{% static 'images/red-dead.jpeg' %}" alt="">
            
                        <img id="slide-3" src="{% static 'images/elden-ring.jpg' %}" alt="">
                    </div>
                    <div class="slider-nav">
                        <a href="#slide-1"></a>
                        <a href="#slide-2"></a>
                        <a href="#slide-3"></a>
                    </div>
              </div>
            </article>
        </section>


        {% block contenido %}
        {% endblock contenido %}

    </main>

    <footer>

    </footer>
    <script src="{% static 'js/bootstrap.js' %}"></script>
</body>
</html>

juegosCom/juegosApp/templates/juegosApp/juegos_gratis.html
{% extends "perfiles/index.html" %}

{% block content %}

<section class="section-1">
  <article class="contenido" >
    <h1> FREE TO PLAY </h1>

    <div class="juegos">
    {% for FreeGame in FreeGames %}
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h4 class="card-title">{{ FreeGame.nombre }}</h4>
        <p class="card-text genero">{{ FreeGame.genero }}</p>
        <p class="card-text">{{ FreeGame.descripcion }}</p>
        <p class="date card-text">{{ FreeGame.lanzamiento }}</p>
        <a class="" href="{% url 'mostrar_juego_gratis' FreeGame.id %}">Ver mas.</a>
        <div>
          {% if user == FreeGame.creador %}
          <a class="delete btn btn-danger" href="{% url 'eliminar_juego_gratis' FreeGame.id %}" method="POST">Eliminar</a>
          {% endif %}
          {% if user == FreeGame.creador %}
          <a class="edit btn btn-primary" href="{% url 'editar_juego_gratis' FreeGame.id %}" method="POST">Editar</a>
          {% endif %}
          <a class="edit btn btn-success" href="{% url 'editar_juego_gratis' FreeGame.id %}" method="POST">Comprar</a>
        </div>
      </div>
      
    </div>
    {% endfor %}
    </div>


    <div class="subtitulo">
      <p>Publica tu juego <b>AHORA</b> <a href="{% url 'crear_juego_gratis' %}">en este enlace. </a></p>
    </div>
    
    <form class="formulario" action="{% url 'buscar_juego_gratis' %}" method="POST">
      {% csrf_token %}
      <h4> Buscador por genero:</h4>
      <input type="text" name="busqueda">
      <input type="submit" name="Buscar por genero">
    </form>

    <ul>

    </ul>
  </article>
</section>
{% endblock content %}

juegosCom/juegosApp/templates/juegosApp/juegos_gratis_info.html
{% extends "perfiles/index.html" %}
{% block content %}
<section class="section-1">
    <article class="contenido" >
      <h1> {{ FreeGame.nombre }} </h1>
  
      <div class="juegos">
      
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h4 class="card-title">{{ FreeGame.nombre }}</h4>
          <p class="date card-text">+{{ FreeGame.clasificacion }}</p>
          <p class="card-text genero">{{ FreeGame.genero }}</p>
          <p class="card-text">{{ FreeGame.descripcion }}</p>
          <p class="date card-text">{{ FreeGame.lanzamiento }}</p>
          <div>
            {% if user == FreeGame.creador %}
            <a class="delete btn btn-danger" href="{% url 'eliminar_juego_gratis' FreeGame.id %}" method="POST">Eliminar</a>
            {% endif %}
            {% if user == FreeGame.creador %}
            <a class="edit btn btn-primary" href="{% url 'editar_juego_gratis' FreeGame.id %}" method="POST">Editar</a>
            {% endif %}
            <a class="edit btn btn-success" href="#" method="POST">Comprar</a>
          </div>
          
        </div>
      </div>
      
    </article>
  </section>
{% endblock content %}

juegosCom/juegosApp/templates/juegosApp/juegos_pagos.html
{% extends "perfiles/index.html" %}
{% load static %}

{% block content %}

<section class="section-1">
  <article class="contenido" >
    <h1> Tendencias </h1>

    <div class="juegos">
    {% for PayGame in PayGames %}
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h4 class="card-title">{{ PayGame.nombre }}</h4>
        <p class="card-text genero">{{ PayGame.genero }}</p>
        <a class="" href="{% url 'mostrar_juego' PayGame.id %}">Ver mas.</a>
        <h6 class="card-title costo">${{ PayGame.costo }}</h6>
        <div>
          {% if user == PayGame.creador %}
          <a class="delete btn btn-danger" href="{% url 'eliminar_juego' PayGame.id %}" method="POST">Eliminar</a>
          {% endif %}
          {% if user == PayGame.creador %}
          <a class="edit btn btn-primary" href="{% url 'editar_juego' PayGame.id %}" method="POST">Editar</a>
          {% endif %}
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            Launch static backdrop modal
          </button>

          <!-- Modal -->
          <script>
            paypal.Buttons({
              // Order is created on the server and the order id is returned
              createOrder() {
                return fetch("/my-server/create-paypal-order", {
                  method: "POST",
                  headers: {
                    "Content-Type": "application/json",
                  },
                  // use the "body" param to optionally pass additional order information
                  // like product skus and quantities
                  body: JSON.stringify({
                    cart: [
                      {
                        sku: "YOUR_PRODUCT_STOCK_KEEPING_UNIT",
                        quantity: "YOUR_PRODUCT_QUANTITY",
                      },
                    ],
                  }),
                })
                .then((response) => response.json())
                .then((order) => order.id);
              }
            }).render('#paypal-button-container');
          </script>
        </div>
        
      </div>
    </div>
    {% endfor %}
    </div>


    <div class="subtitulo">
      <p>Publica tu juego <b>AHORA</b> <a href="{% url 'crear_juego' %}">en este enlace. </a></p>
    </div>
    
    <form class="formulario" action="{% url 'buscar_juego' %}" method="POST">
      {% csrf_token %}
      <h4> Buscador por precios:</h4>
      <input type="text" name="busqueda">
      <input type="submit" name="Buscar por costo">
    </form>

    <ul>

    </ul>
  </article>
</section>
{% endblock content %}

juegosCom/juegosApp/templates/juegosApp/juegos_pagos_info.html
{% extends "perfiles/index.html" %}
{% block content %}
<section class="section-1">
    <article class="contenido" >
      <h1> {{ PayGame.nombre }} </h1>
  
      <div class="juegos">
      
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h4 class="card-title">{{ PayGame.nombre }}</h4>
          <p class="date card-text">+{{ PayGame.clasificacion }}</p>
          <p class="card-text genero">{{ PayGame.genero }}</p>
          <p class="card-text">{{ PayGame.descripcion }}</p>
          <p class="date card-text">{{ PayGame.lanzamiento }}</p>
          <h6 class="card-title costo">${{ PayGame.costo }}</h6>
          <div>
            {% if user == PayGame.creador %}
            <a class="delete btn btn-danger" href="{% url 'eliminar_juego' PayGame.id %}" method="POST">Eliminar</a>
            {% endif %}
            {% if user == PayGame.creador %}
            <a class="edit btn btn-primary" href="{% url 'editar_juego' PayGame.id %}" method="POST">Editar</a>
            {% endif %}
            <a class="edit btn btn-success" href="#" method="POST">Comprar</a>
          </div>
          
        </div>
      </div>
      
    </article>
  </section>
{% endblock content %}

juegosCom/juegosApp/templates/juegosApp/valid_forms.html
{% extends "perfiles/index.html" %}

{% block content %}
<section class="section-3">
  <div>
    <h1>Publica tu videojuego!</h1>
    
    <form method="POST">
        {% csrf_token %}
        
        <div class="form-group">
          <label for="id_nombre">Nombre:</label>
          {{ formulario.nombre }}
        </div>
        
        <div class="form-group-desc">
          <label for="id_descripcion">Descripción:</label>
          {{ formulario.descripcion }}
        </div>
        
        <div class="form-group">
          <label for="id_genero">Género:</label>
          {{ formulario.genero }}
        </div>
        
        <div class="form-group">
          <label for="id_lanzamiento">Lanzamiento:</label>
          {{ formulario.lanzamiento }}
        </div>
        
        <div class="form-group">
          <label for="id_clasificacion">Clasificación:</label>
          {{ formulario.clasificacion }}
        </div>
        
        <div class="form-group">
          <label for="id_costo">Costo:</label>
          {{ formulario.costo }}
        </div>
        
        <button class="btn btn-light" type="submit">Enviar</button>
      </form>
    </div>
</section>
{% endblock content %}

juegosCom/juegosApp/templates/juegosApp/valid_forms_gratis.html
{% extends "perfiles/index.html" %}

{% block content %}
<section class="section-3">
  <div>
    <h1>Publica tu videojuego!</h1>
    
    <form method="POST">
        {% csrf_token %}
        
        <div class="form-group">
          <label for="id_nombre">Nombre:</label>
          {{ formulario.nombre }}
        </div>
        
        <div class="form-group-desc">
          <label for="id_descripcion">Descripción:</label>
          {{ formulario.descripcion }}
        </div>
        
        <div class="form-group">
          <label for="id_genero">Género:</label>
          {{ formulario.genero }}
        </div>
        
        <div class="form-group">
          <label for="id_lanzamiento">Lanzamiento:</label>
          {{ formulario.lanzamiento }}
        </div>
        
        <div class="form-group">
          <label for="id_clasificacion">Clasificación:</label>
          {{ formulario.clasificacion }}
        </div>
        
        <button class="btn btn-light" type="submit">Enviar</button>
      </form>
    </div>
</section>
{% endblock content %}